# Generated by Django 4.2.1 on 2023-07-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote", "0002_quoteuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="tossup",
            name="power_position",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="tossup",
            name="representation",
            field=models.JSONField(null=True),
        ),
    ]
