# Generated by Django 4.2.1 on 2023-07-10 21:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("quote", "0003_distribution_alter_bonuspart_part_number_category"),
        ("quote", "0004_remove_category_subcategory_bonus_cateogry_and_more"),
        ("quote", "0005_alter_packet_tournament"),
        ("quote", "0006_rename_cateogry_bonus_category_and_more"),
        (
            "quote",
            "0007_rename_number_bonuses_per_packet_distribution_num_bonuses_and_more",
        ),
        ("quote", "0008_remove_bonus_category_remove_tossup_category"),
        ("quote", "0009_bonus_category_tossup_category"),
    ]

    dependencies = [
        ("quote", "0002_quoteuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Distribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_tossups",
                    models.PositiveSmallIntegerField(default=20, null=True),
                ),
                (
                    "num_bonuses",
                    models.PositiveSmallIntegerField(default=20, null=True),
                ),
                (
                    "tournament",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quote.tournament",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="bonuspart",
            name="part_number",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="tossup",
            name="difficulty",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="packet",
            name="tournament",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quote.tournament",
            ),
        ),
        migrations.AlterField(
            model_name="packet",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quote.tournament"
            ),
        ),
        migrations.CreateModel(
            name="DistributionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("min_tossups", models.PositiveSmallIntegerField(null=True)),
                ("max_tossups", models.PositiveSmallIntegerField(null=True)),
                ("min_bonuses", models.PositiveSmallIntegerField(null=True)),
                ("max_bonuses", models.PositiveSmallIntegerField(null=True)),
                (
                    "distribution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quote.distribution",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="quote.distributioncategory",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="bonus",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quote.distributioncategory",
            ),
        ),
        migrations.AddField(
            model_name="tossup",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quote.distributioncategory",
            ),
        ),
    ]
