# Generated by Django 4.2.1 on 2023-07-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote", "0003_tossup_power_position_tossup_representation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tossup",
            name="power_position",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tossup",
            name="representation",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
