# Generated by Django 4.2.1 on 2023-07-24 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quote", "0003_distributions_and_minor_alterations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distribution",
            name="tournament",
        ),
        migrations.RemoveField(
            model_name="distributioncategory",
            name="parent",
        ),
        migrations.AddField(
            model_name="distribution",
            name="name",
            field=models.CharField(default="name", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tournament",
            name="distribution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="quote.distribution",
            ),
        ),
        migrations.AlterField(
            model_name="bonuspart",
            name="part_number",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="quote.category",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="distributioncategory",
            name="categories",
            field=models.ManyToManyField(to="quote.category"),
        ),
    ]
