# Generated by Django 4.2.1 on 2023-07-19 03:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote", "0004_alter_tossup_power_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tossup",
            name="difficulty",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
