# Generated by Django 4.2.1 on 2023-07-19 03:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quote", "0005_alter_tossup_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tossup",
            name="difficulty",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tossup",
            name="packet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quote.packet",
            ),
        ),
    ]
